export const ACTIONS = {
    RADIOS_GET_DATA_REQUEST: 'RADIOS_GET_DATA_REQUEST',
    RADIOS_GET_DATA_FAILED: 'RADIOS_GET_DATA_FAILED',
    RADIOS_GET_DATA_SUCCEED: 'RADIOS_GET_DATA_SUCCEED',
    RADIOS_POPULATE_DATA: 'RADIOS_POPULATE_DATA',
}